[2024-11-06T04:32:44.881+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-06T04:32:44.988+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_dag.database_tasks.check_integrity manual__2024-11-06T02:17:50.795367+00:00 [queued]>
[2024-11-06T04:32:44.996+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_dag.database_tasks.check_integrity manual__2024-11-06T02:17:50.795367+00:00 [queued]>
[2024-11-06T04:32:44.997+0000] {taskinstance.py:2865} INFO - Starting attempt 3 of 4
[2024-11-06T04:32:45.014+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): database_tasks.check_integrity> on 2024-11-06 02:17:50.795367+00:00
[2024-11-06T04:32:45.017+0000] {standard_task_runner.py:72} INFO - Started process 55094 to run task
[2024-11-06T04:32:45.020+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'database_tasks.check_integrity', 'manual__2024-11-06T02:17:50.795367+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpq5e831qm']
[2024-11-06T04:32:45.020+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask database_tasks.check_integrity
[2024-11-06T04:32:45.069+0000] {task_command.py:467} INFO - Running <TaskInstance: test_dag.database_tasks.check_integrity manual__2024-11-06T02:17:50.795367+00:00 [running]> on host 64e2411a2cf3
[2024-11-06T04:32:45.146+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='veil' AIRFLOW_CTX_DAG_ID='test_dag' AIRFLOW_CTX_TASK_ID='database_tasks.check_integrity' AIRFLOW_CTX_EXECUTION_DATE='2024-11-06T02:17:50.795367+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-06T02:17:50.795367+00:00'
[2024-11-06T04:32:45.147+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-06T04:32:45.164+0000] {logging_mixin.py:190} INFO - Connection to PostgreSQL DB successful
[2024-11-06T04:32:45.164+0000] {logging_mixin.py:190} INFO - /app/***/dags/database/integrity_check.py
[2024-11-06T04:32:45.309+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-06T04:32:45.322+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-06T04:32:45.322+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_dag, task_id=database_tasks.check_integrity, run_id=manual__2024-11-06T02:17:50.795367+00:00, execution_date=20241106T021750, start_date=20241106T043244, end_date=20241106T043245
[2024-11-06T04:32:45.362+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-06T04:32:45.379+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-06T04:32:45.382+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
