[2024-11-06T08:43:06.101+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-06T08:43:06.261+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.database_tasks.check_integrity manual__2024-11-06T06:42:05.001646+00:00 [queued]>
[2024-11-06T08:43:06.272+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.database_tasks.check_integrity manual__2024-11-06T06:42:05.001646+00:00 [queued]>
[2024-11-06T08:43:06.273+0000] {taskinstance.py:2865} INFO - Starting attempt 3 of 4
[2024-11-06T08:43:06.297+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): database_tasks.check_integrity> on 2024-11-06 06:42:05.001646+00:00
[2024-11-06T08:43:06.301+0000] {standard_task_runner.py:72} INFO - Started process 32850 to run task
[2024-11-06T08:43:06.306+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'database_tasks.check_integrity', 'manual__2024-11-06T06:42:05.001646+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmptret1wcl']
[2024-11-06T08:43:06.307+0000] {standard_task_runner.py:105} INFO - Job 23: Subtask database_tasks.check_integrity
[2024-11-06T08:43:06.385+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.database_tasks.check_integrity manual__2024-11-06T06:42:05.001646+00:00 [running]> on host 9694314923d2
[2024-11-06T08:43:06.500+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='veil' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='database_tasks.check_integrity' AIRFLOW_CTX_EXECUTION_DATE='2024-11-06T06:42:05.001646+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-06T06:42:05.001646+00:00'
[2024-11-06T08:43:06.501+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-06T08:43:06.520+0000] {logging_mixin.py:190} INFO - Connection to PostgreSQL DB successful
[2024-11-06T08:43:06.520+0000] {logging_mixin.py:190} INFO - /app/***/dags/database/integrity_check.py
[2024-11-06T08:43:06.692+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-06T08:43:06.709+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-06T08:43:06.710+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=database_tasks.check_integrity, run_id=manual__2024-11-06T06:42:05.001646+00:00, execution_date=20241106T064205, start_date=20241106T084306, end_date=20241106T084306
[2024-11-06T08:43:06.734+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-06T08:43:06.756+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-06T08:43:06.759+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
